@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Oct 12 11:13:05 +0200 2023
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_riscv_wrapper_behav -key {Behavioral:sim_1:Functional:tb_riscv_wrapper} -tclbatch tb_riscv_wrapper.tcl -protoinst "protoinst_files/RISCV_bd.protoinst" -protoinst "protoinst_files/RISCV_demonstrator.protoinst" -view H:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.srcs/sim_1/imports/waveform/tb_top_behav.wcfg -view H:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.srcs/sim_1/imports/waveform/tb_RISCV_behav.wcfg -view H:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.srcs/sim_1/imports/waveform/tb_RISCV_demonstrator_behav.wcfg -log simulate.log"
call xsim  tb_riscv_wrapper_behav -key {Behavioral:sim_1:Functional:tb_riscv_wrapper} -tclbatch tb_riscv_wrapper.tcl -protoinst "protoinst_files/RISCV_bd.protoinst" -protoinst "protoinst_files/RISCV_demonstrator.protoinst" -view H:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.srcs/sim_1/imports/waveform/tb_top_behav.wcfg -view H:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.srcs/sim_1/imports/waveform/tb_RISCV_behav.wcfg -view H:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.srcs/sim_1/imports/waveform/tb_RISCV_demonstrator_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
