# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.srcs/sources_1/bd/RISCV_bd/ip/RISCV_bd_axi_gpio_0_0/RISCV_bd_axi_gpio_0_0.xci
# IP: The module: 'RISCV_bd_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.gen/sources_1/bd/RISCV_bd/ip/RISCV_bd_axi_gpio_0_0/RISCV_bd_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: h:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.gen/sources_1/bd/RISCV_bd/ip/RISCV_bd_axi_gpio_0_0/RISCV_bd_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: h:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.gen/sources_1/bd/RISCV_bd/ip/RISCV_bd_axi_gpio_0_0/RISCV_bd_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: H:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.srcs/sources_1/bd/RISCV_bd/ip/RISCV_bd_axi_gpio_0_0/RISCV_bd_axi_gpio_0_0.xci
# IP: The module: 'RISCV_bd_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.gen/sources_1/bd/RISCV_bd/ip/RISCV_bd_axi_gpio_0_0/RISCV_bd_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: h:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.gen/sources_1/bd/RISCV_bd/ip/RISCV_bd_axi_gpio_0_0/RISCV_bd_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: h:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.gen/sources_1/bd/RISCV_bd/ip/RISCV_bd_axi_gpio_0_0/RISCV_bd_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
