# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo_Z7_Master.xdc

# Block Designs: bd/RISCV_bd/RISCV_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_bd || ORIG_REF_NAME==RISCV_bd} -quiet] -quiet

# IP: bd/RISCV_bd/ip/RISCV_bd_clk_wiz_0_0/RISCV_bd_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_bd_clk_wiz_0_0 || ORIG_REF_NAME==RISCV_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/RISCV_bd/ip/RISCV_bd_proc_sys_reset_0_0/RISCV_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==RISCV_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/RISCV_bd/ip/RISCV_bd_axi_gpio_0_0/RISCV_bd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_bd_axi_gpio_0_0 || ORIG_REF_NAME==RISCV_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/RISCV_bd/ip/RISCV_bd_riscv_wrapper_0_1/RISCV_bd_riscv_wrapper_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_bd_riscv_wrapper_0_1 || ORIG_REF_NAME==RISCV_bd_riscv_wrapper_0_1} -quiet] -quiet

# XDC: h:/TesiMagistrale/Github/RISCV_Enc_Load_Store/RISCV-Load-Store-with-OTP-Encription/RISCV_project/RISCV_project.gen/sources_1/bd/RISCV_bd/RISCV_bd_ooc.xdc
